spring:
    data:
        mongodb:
            auto-index-creation: true
            authentication-database: admin
            username: admin
            password: admin
            database: catalogue
            port: 27017
            host: localhost
server.port: 8080